### ISSUE TITLE
Method Not Allowed on /laravel-websockets/statistics

### ISSUE THREAD

**Issue by claystation** [beyondcode/laravel-websockets#110]
Hey,

My logs are getting spammed with stacktraces of a Method not allowed call (happening each time i send out an event). This happens locally but also on staging (We are not in production yet). The websockets work fine on both environments. I just dont get the stacktrace.

This is the stacktrace:

```
"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0):  at /var/www/website.com/releases/13/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:255)
[stacktrace]
#0 /var/www/website.com/releases/13/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php(242): Illuminate\\Routing\\RouteCollection->methodNotAllowed(Array)
#1 /var/www/website.com/releases/13/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php(176): Illuminate\\Routing\\RouteCollection->getRouteForMethods(Object(Illuminate\\Http\\Request), Array)
#2 /var/www/website.com/releases/13/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\RouteCollection->match(Object(Illuminate\\Http\\Request))
#3 /var/www/website.com/releases/13/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->findRoute(Object(Illuminate\\Http\\Request))
#4 /var/www/website.com/releases/13/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#5 /var/www/website.com/releases/13/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#6 /var/www/website.com/releases/13/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#7 /var/www/website.com/releases/13/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#8 /var/www/website.com/releases/13/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#9 /var/www/website.com/releases/13/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#10 /var/www/website.com/releases/13/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#11 /var/www/website.com/releases/13/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#12 /var/www/website.com/releases/13/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#13 /var/www/website.com/releases/13/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#14 /var/www/website.com/releases/13/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 /var/www/website.com/releases/13/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /var/www/website.com/releases/13/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#17 /var/www/website.com/releases/13/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /var/www/website.com/releases/13/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /var/www/website.com/releases/13/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /var/www/website.com/releases/13/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /var/www/website.com/releases/13/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /var/www/website.com/releases/13/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /var/www/website.com/releases/13/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#24 /var/www/website.com/releases/13/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#25 /var/www/website.com/releases/13/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#26 {main}
"}
```

Debugging brought me here (I have the dashboard on `/application/laravel-websockets` so that is correct)

```
[2019-02-14 16:08:25] staging.ERROR: Request: {"request":"[object] (Illuminate\\Http\\Request: GET /application/laravel-websockets/statistics HTTP/1.0
Content-Length:
Content-Type:
Host:           website.com
User-Agent:     React/alpha
)"
```

`php artisan route:list` shows me the following

```
|        | GET|HEAD      | application/laravel-websockets                        |                        | BeyondCode\LaravelWebSockets\Dashboard\Http\Controllers\ShowDashboard                               | web,BeyondCode\LaravelWebSockets\Dashboard\Http\Middleware\Authorize,role:Webmaster  |
|        | GET|HEAD      | application/laravel-websockets/api/{appId}/statistics |                        | BeyondCode\LaravelWebSockets\Dashboard\Http\Controllers\DashboardApiController@getStatistics        | web,BeyondCode\LaravelWebSockets\Dashboard\Http\Middleware\Authorize,role:Webmaster  |
|        | POST          | application/laravel-websockets/auth                   |                        | BeyondCode\LaravelWebSockets\Dashboard\Http\Controllers\AuthenticateDashboard                       | web,BeyondCode\LaravelWebSockets\Dashboard\Http\Middleware\Authorize,role:Webmaster  |
|        | POST          | application/laravel-websockets/event                  |                        | BeyondCode\LaravelWebSockets\Dashboard\Http\Controllers\SendMessage                                 | web,BeyondCode\LaravelWebSockets\Dashboard\Http\Middleware\Authorize,role:Webmaster  |
|        | POST          | application/laravel-websockets/statistics             |                        | BeyondCode\LaravelWebSockets\Statistics\Http\Controllers\WebSocketStatisticsEntriesController@store | BeyondCode\LaravelWebSockets\Statistics\Http\Middleware\Authorize                    |
```

Which would explain the HTTP 405. But why is the Laravel app trying to do a GET on `/application/laravel-websockets/statistics`? Am i missing something obvious or is this a simple bug?

Thanks in advance!

**Comment by canhkieu** [comment]
Use spatie/laravel-cors to fix this problem.
