### ISSUE TITLE
Unhandled promise rejection with TypeError: React\Http\Io\ClientRequestStream::closeError(): Argument #1 ($error) must be of type Exception, TypeError given, called in /data/wwwroot/wallet/vendor/react/promise/src/Internal/RejectedPromise.php on line 73 in /data/wwwroot/wallet/vendor/react/http/src/Io/ClientRequestStream.php:238

### ISSUE THREAD

**Issue by phpmac** [beyondcode/laravel-websockets#1158]
```
Starting the WebSocket server on port 6001...
Unhandled promise rejection with TypeError: React\Http\Io\ClientRequestStream::closeError(): Argument #1 ($error) must be of type Exception, TypeError given, called in /data/wwwroot/wallet/vendor/react/promise/src/Internal/RejectedPromise.php on line 73 in /data/wwwroot/wallet/vendor/react/http/src/Io/ClientRequestStream.php:238
Stack trace:
#0 /data/wwwroot/wallet/vendor/react/promise/src/Internal/RejectedPromise.php(73): React\Http\Io\ClientRequestStream->closeError()
#1 /data/wwwroot/wallet/vendor/react/promise/src/Promise.php(43): React\Promise\Internal\RejectedPromise->then()
#2 /data/wwwroot/wallet/vendor/react/http/src/Io/ClientRequestStream.php(67): React\Promise\Promise->then()
#3 /data/wwwroot/wallet/vendor/react/http/src/Io/ClientRequestStream.php(122): React\Http\Io\ClientRequestStream->writeHead()
#4 /data/wwwroot/wallet/vendor/react/http/src/Io/ClientRequestStream.php(135): React\Http\Io\ClientRequestStream->write()
#5 /data/wwwroot/wallet/vendor/react/http/src/Io/Sender.php(152): React\Http\Io\ClientRequestStream->end()
#6 /data/wwwroot/wallet/vendor/react/http/src/Io/Transaction.php(146): React\Http\Io\Sender->send()
#7 /data/wwwroot/wallet/vendor/react/http/src/Io/Transaction.php(83): React\Http\Io\Transaction->next()
#8 /data/wwwroot/wallet/vendor/react/http/src/Browser.php(853): React\Http\Io\Transaction->send()
#9 /data/wwwroot/wallet/vendor/react/http/src/Browser.php(176): React\Http\Browser->requestMayBeStreaming()
#10 /data/wwwroot/wallet/vendor/beyondcode/laravel-websockets/src/Statistics/Logger/HttpStatisticsLogger.php(81): React\Http\Browser->post()
#11 /data/wwwroot/wallet/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(353): BeyondCode\LaravelWebSockets\Statistics\Logger\HttpStatisticsLogger->save()
#12 /data/wwwroot/wallet/vendor/beyondcode/laravel-websockets/src/Console/StartWebSocketServer.php(75): Illuminate\Support\Facades\Facade::__callStatic()
#13 /data/wwwroot/wallet/vendor/react/event-loop/src/Timer/Timers.php(101): BeyondCode\LaravelWebSockets\Console\StartWebSocketServer->BeyondCode\LaravelWebSockets\Console\{closure}()
#14 /data/wwwroot/wallet/vendor/react/event-loop/src/StreamSelectLoop.php(185): React\EventLoop\Timer\Timers->tick()
#15 /data/wwwroot/wallet/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php(74): React\EventLoop\StreamSelectLoop->run()
#16 /data/wwwroot/wallet/vendor/beyondcode/laravel-websockets/src/Console/StartWebSocketServer.php(155): Ratchet\Server\IoServer->run()
#17 /data/wwwroot/wallet/vendor/beyondcode/laravel-websockets/src/Console/StartWebSocketServer.php(52): BeyondCode\LaravelWebSockets\Console\StartWebSocketServer->startWebSocketServer()
#18 /data/wwwroot/wallet/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): BeyondCode\LaravelWebSockets\Console\StartWebSocketServer->handle()
#19 /data/wwwroot/wallet/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#20 /data/wwwroot/wallet/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#21 /data/wwwroot/wallet/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#22 /data/wwwroot/wallet/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#23 /data/wwwroot/wallet/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\Container\Container->call()
#24 /data/wwwroot/wallet/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
#25 /data/wwwroot/wallet/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\Component\Console\Command\Command->run()
#26 /data/wwwroot/wallet/vendor/symfony/console/Application.php(1081): Illuminate\Console\Command->run()
#27 /data/wwwroot/wallet/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand()
#28 /data/wwwroot/wallet/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun()
#29 /data/wwwroot/wallet/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run()
#30 /data/wwwroot/wallet/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#31 {main}
```

**Comment by phpmac** [comment]
composer require react/promise:^2.3

**Comment by cerw** [comment]
Hello, having same issues..whats the solutions> Downgrade to 2.9?

**Comment by mikebronner** [comment]
Just putting this out there as an honest question: wouldn't it be better if this package specifies the dependency versions it requires to function? Are there any pitfalls to that approach? If not, perhaps a PR is appropriate?

**Comment by maximal** [comment]
@mikebronner is right here, imo.

**Comment by Waleedx249i** [comment]
how can i solve this issue??
