### ISSUE TITLE
Error sending plain text client message

### ISSUE THREAD

**Issue by azcoppen** [beyondcode/laravel-websockets#377]
When receiving a client message, a custom websocket handler class (blank stub, no extra code) generates the exception: `Trying to get property 'id' of non-object`.

Laravel 7, package v 1.4 (latest)

To reproduce:

1. Set up custom handler as per the documentation. Run `websockets:serve`
2. Connect with any websocket client (Websocket King, Simple Client, Websocat etc). 
3. Send plain text word, e.g. "HELLO"
4. Check console - error appears.

Output:

```
Starting the WebSocket server on port 6001...
New connection opened for app key .
Connection id 513705537.594463571 sending message OPENED
Exception `ErrorException` thrown: `Trying to get property 'id' of non-object`
Unknown app id: exception `ErrorException` thrown: `Trying to get property 'id' of non-object`.
Connection id 513705537.594463571 sending message ERROR: Trying to get property 'id' of non-object
Connection id 513705537.594463571 sending message /home/acme/WEBHOSTS/Project/vendor/beyondcode/laravel-websockets/src/Server/Logger/WebsocketsLogger.php
Connection id 513705537.594463571 sending message 41
Connection id 513705537.594463571 sending message #0 /home/acme/WEBHOSTS/Project/vendor/beyondcode/laravel-websockets/src/Server/Logger/WebsocketsLogger.php(41): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /home/acme/WEBHOSTS/Project/vendor/cboden/ratchet/src/Ratchet/WebSocket/WsServer.php(71): BeyondCode\LaravelWebSockets\Server\Logger\WebsocketsLogger->onMessage()
#2 /home/acme/WEBHOSTS/Project/vendor/cboden/ratchet/src/Ratchet/WebSocket/WsServer.php(131): Ratchet\WebSocket\WsServer->Ratchet\WebSocket\{closure}()
#3 /home/acme/WEBHOSTS/Project/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(200): Ratchet\WebSocket\WsServer->Ratchet\WebSocket\{closure}()
#4 /home/acme/WEBHOSTS/Project/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(153): Ratchet\RFC6455\Messaging\MessageBuffer->processData()
#5 /home/acme/WEBHOSTS/Project/vendor/cboden/ratchet/src/Ratchet/WebSocket/WsServer.php(153): Ratchet\RFC6455\Messaging\MessageBuffer->onData()
#6 /home/acme/WEBHOSTS/Project/vendor/cboden/ratchet/src/Ratchet/Http/Router.php(76): Ratchet\WebSocket\WsServer->onMessage()
#7 /home/acme/WEBHOSTS/Project/vendor/beyondcode/laravel-websockets/src/Server/OriginCheck.php(38): Ratchet\Http\Router->onMessage()
#8 /home/acme/WEBHOSTS/Project/vendor/cboden/ratchet/src/Ratchet/Http/HttpServer.php(54): BeyondCode\LaravelWebSockets\Server\OriginCheck->onMessage()
#9 /home/acme/WEBHOSTS/Project/vendor/beyondcode/laravel-websockets/src/Server/Logger/HttpLogger.php(35): Ratchet\Http\HttpServer->onMessage()
#10 /home/acme/WEBHOSTS/Project/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php(112): BeyondCode\LaravelWebSockets\Server\Logger\HttpLogger->onMessage()
#11 /home/acme/WEBHOSTS/Project/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php(95): Ratchet\Server\IoServer->handleData()
#12 /home/acme/WEBHOSTS/Project/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Ratchet\Server\IoServer->Ratchet\Server\{closure}()
#13 /home/acme/WEBHOSTS/Project/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit()
#14 /home/acme/WEBHOSTS/Project/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}()
#15 /home/acme/WEBHOSTS/Project/vendor/react/stream/src/DuplexResourceStream.php(193): Evenement\EventEmitter->emit()
#16 [internal function]: React\Stream\DuplexResourceStream->handleData()
#17 /home/acme/WEBHOSTS/Project/vendor/react/event-loop/src/StreamSelectLoop.php(236): call_user_func()
#18 /home/acme/WEBHOSTS/Project/vendor/react/event-loop/src/StreamSelectLoop.php(205): React\EventLoop\StreamSelectLoop->waitForStreamActivity()
#19 /home/acme/WEBHOSTS/Project/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php(74): React\EventLoop\StreamSelectLoop->run()
#20 /home/acme/WEBHOSTS/Project/vendor/beyondcode/laravel-websockets/src/Console/StartWebSocketServer.php(135): Ratchet\Server\IoServer->run()
#21 /home/acme/WEBHOSTS/Project/vendor/beyondcode/laravel-websockets/src/Console/StartWebSocketServer.php(48): BeyondCode\LaravelWebSockets\Console\StartWebSocketServer->startWebSocketServer()
#22 [internal function]: BeyondCode\LaravelWebSockets\Console\StartWebSocketServer->handle()
#23 /home/acme/WEBHOSTS/Project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array()
#24 /home/acme/WEBHOSTS/Project/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#25 /home/acme/WEBHOSTS/Project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\Container\Util::unwrapIfClosure()
#26 /home/acme/WEBHOSTS/Project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#27 /home/acme/WEBHOSTS/Project/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\Container\BoundMethod::call()
#28 /home/acme/WEBHOSTS/Project/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call()
#29 /home/acme/WEBHOSTS/Project/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute()
#30 /home/acme/WEBHOSTS/Project/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#31 /home/acme/WEBHOSTS/Project/vendor/symfony/console/Application.php(912): Illuminate\Console\Command->run()
#32 /home/acme/WEBHOSTS/Project/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand()
#33 /home/acme/WEBHOSTS/Project/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun()
#34 /home/acme/WEBHOSTS/Project/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run()
#35 /home/acme/WEBHOSTS/Project/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#36 /home/acme/WEBHOSTS/Project/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
```

**Comment by BenMstfa** [comment]
How did you implement you approach to enable client_messages? Will appreciate it if you post a code snippet of your implementation.

**Comment by BenMstfa** [comment]
I think you need to assign an ID to the connection and socket id here is an approach I've found on StackOverflow but I couldn't find the exact question to refer to

`function onOpen(ConnectionInterface $conn)
    {
        /* @var $request RequestInterface */
        // $request = $conn->httpRequest;
        $socketId = GeneralHelper::generateSocketID();
        $conn->socketId = $socketId;
        $conn->app = App::findById(866642);
    }`
and generateSocketID function code is: 

`public static function generateSocketID()
    {
        return sprintf('%d.%d', random_int(1, 1000000000), random_int(1, 1000000000));
    }`

**Comment by azcoppen** [comment]
@BenMstfa I just used the out-of-the-box example from the docs with no changes, then added that code on top (which i also found with a search). Each produced the same result when receiving a client message.

**Comment by BenMstfa** [comment]
Please notice the first line of the exception trace above: 

```php
Connection id 513705537.594463571 sending message /home/acme/WEBHOSTS/Project/vendor/beyondcode/laravel-websockets/src/Server/Logger/WebsocketsLogger.php
```

If you open `WebsocketsLogger.php` class you will find the following onMessage function 

```php 

public function onMessage(ConnectionInterface $connection, MessageInterface $message)
    {
        $this->info("{$connection->app->id}: connection id {$connection->socketId} received message: {$message->getPayload()}.");

        $this->app->onMessage(ConnectionLogger::decorate($connection), $message);
    }
```

that function tries to access the app ID of your pusher configuration so I think you may forget to configure pusher application in the `broadcasting.php` file, It should be as follows: 

```php

'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'useTLS' => true,
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => 'http'
            ],
        ],
```

and in your environment assign any random values to the following keys: 

```php

PUSHER_APP_ID=154545454
PUSHER_APP_KEY=adssdfsdf
PUSHER_APP_SECRET=115145454545
PUSHER_APP_CLUSTER=eu
```

I wish this helps.

**Comment by azcoppen** [comment]
@BenMstfa Appreciate the continued help. My pusher vars are all defined - i have them running through the Pusher console no problem at all.

I've actually switched to Crossbar (https://crossbar.io/docs/HTTP-Bridge/) as it's been horribly difficult trying to deal with inbound comms, and particularly the lack of support for WAMP. Ratchet doesn't do WAMP2 (only v1) and Thruway doesn't support Laravel 7 (uses Symfony 4 event dispatcher). Some of them haven't been updated for years!
