### ISSUE TITLE
[2.x] Target [BeyondCode\LaravelWebSockets\Contracts\ChannelManager] is not instantiable

### ISSUE THREAD

**Issue by vikas5914** [beyondcode/laravel-websockets#531]
Just create a brand new Laravel v8 App with v2.0.0-beta.20. 

When trying to send a demo event from the dashboard , getting 500 error with the following error msg: 

```
[2020-09-15 17:18:47] local.ERROR: Target [BeyondCode\LaravelWebSockets\Contracts\ChannelManager] is not instantiable. {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target [BeyondCode\\LaravelWebSockets\\Contracts\\ChannelManager] is not instantiable. at /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Container/Container.php:1017)
[stacktrace]
#0 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Container/Container.php(818): Illuminate\\Container\\Container->notInstantiable('BeyondCode\\\\Lara...')
#1 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build('BeyondCode\\\\Lara...')
#2 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve('BeyondCode\\\\Lara...', Array, true)
#3 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve('BeyondCode\\\\Lara...', Array)
#4 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make('BeyondCode\\\\Lara...', Array)
#5 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(79): Illuminate\\Foundation\\Application->make('BeyondCode\\\\Lara...')
#6 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(48): Illuminate\\Routing\\ControllerDispatcher->transformDependency(Object(ReflectionParameter), Array, Object(stdClass))
#7 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(28): Illuminate\\Routing\\ControllerDispatcher->resolveMethodDependencies(Array, Object(ReflectionMethod))
#8 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(41): Illuminate\\Routing\\ControllerDispatcher->resolveClassMethodDependencies(Array, Object(BeyondCode\\LaravelWebSockets\\Dashboard\\Http\\Controllers\\SendMessage), '__invoke')
#9 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Routing/Route.php(255): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(BeyondCode\\LaravelWebSockets\\Dashboard\\Http\\Controllers\\SendMessage), '__invoke')
#10 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#11 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(691): Illuminate\\Routing\\Route->run()
#12 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#13 /shared/httpd/expo-socket/socket-project/vendor/beyondcode/laravel-websockets/src/Dashboard/Http/Middleware/Authorize.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): BeyondCode\\LaravelWebSockets\\Dashboard\\Http\\Middleware\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#23 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(693): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#30 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(668): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#31 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(634): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#32 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#33 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#34 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#35 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(87): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /shared/httpd/expo-socket/socket-project/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /shared/httpd/expo-socket/socket-project/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#49 /shared/httpd/expo-socket/socket-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#50 /shared/httpd/expo-socket/socket-project/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#51 {main}
"} 
```

**Comment by vikas5914** [comment]
I have done a few things. 

I have registered the ChannelManager in WebSockerServiceProvider.php Like this: 

```
$this->app->singleton(Contracts\ChannelManager::class, function () {

    $replicationMode = config('websockets.replication.mode', 'local');

    $class = config("websockets.replication.modes.{$replicationMode}.channel_manager");

    return new $class;
});
```

After that I run the following command in the tinker : 

`app('BeyondCode\LaravelWebSockets\Contracts\ChannelManager')`

and got the following error: 

```
TypeError: Too few arguments to function BeyondCode/LaravelWebSockets/ChannelManagers/LocalChannelManager::__construct(), 0 passed in /shared/httpd/expo-socket/socket-project/vendor/beyondcode/laravel-websockets/src/WebSocketsServiceProvider.php on line 137 and at least 1 expected
```

**Comment by rennokki** [comment]
Fixed in `beta.21`: https://github.com/beyondcode/laravel-websockets/releases/tag/2.0.0-beta.21
