### ISSUE TITLE
BroadcastExcepetion on PusherBroadcaster.php:121 when trying to broadcast an event using Laravel-Websockets

### ISSUE THREAD

**Issue by mathewparet** [beyondcode/laravel-websockets#557]
I'm trying to use Laravel-Websockets for broadcasting. I had some trouble getting the socket connected, but now that is working. Now this is where I am stuck.

Socket connection works:

```
Starting the WebSocket server on port 6001...
New connection opened for app key gkey.
Connection id 716018866.942584912 sending message {"event":"pusher:connection_established","data":"{\"socket_id\":\"716018866.942584912\",\"activity_timeout\":30}"}
gid: connection id 716018866.942584912 received message: {"event":"pusher:ping","data":{}}.
Connection id 716018866.942584912 sending message {"event":"pusher:pong"}
gid: connection id 716018866.942584912 received message: {"event":"pusher:ping","data":{}}.
Connection id 716018866.942584912 sending message {"event":"pusher:pong"}
```

I created an event - ```OvpnStatusUpdated```:

```
<?php

namespace App\Events;

use Illuminate\Broadcasting\Channel;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Broadcasting\PresenceChannel;
use Illuminate\Broadcasting\PrivateChannel;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\SerializesModels;

class OvpnStatusUpdated implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $connections;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct($connections)
    {
        $this->connections = $connections;
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return \Illuminate\Broadcasting\Channel|array
     */
    public function broadcastOn()
    {
        return new PrivateChannel('OvpnStatus');
    }
}
```

But when I invoke the event, I get an exception:

```
Psy Shell v0.10.0 (PHP 7.3.11 — cli) by Justin Hileman
>>> use App\Events\OvpnStatusUpdated;
>>> event(new OvpnStatusUpdated('hi'));
=> [
     null,
   ]
```

```
[2020-09-27 19:30:06] local.ERROR:  {"exception":"[object] (Illuminate\\Broadcasting\\BroadcastException(code: 0):  at /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php:121)
[stacktrace]
#0 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastEvent.php(64): Illuminate\\Broadcasting\\Broadcasters\\PusherBroadcaster->broadcast(Array, 'App\\\\Events\\\\Ovpn...', Array)
#1 [internal function]: Illuminate\\Broadcasting\\BroadcastEvent->handle(Object(Illuminate\\Broadcasting\\Broadcasters\\PusherBroadcaster))
#2 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#3 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#5 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#6 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#7 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#8 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Illuminate\\Broadcasting\\BroadcastEvent))
#9 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Broadcasting\\BroadcastEvent))
#10 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#11 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Illuminate\\Broadcasting\\BroadcastEvent), false)
#12 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(Illuminate\\Broadcasting\\BroadcastEvent))
#13 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Broadcasting\\BroadcastEvent))
#14 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#15 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Object(Illuminate\\Broadcasting\\BroadcastEvent))
#16 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Array)
#17 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\\Queue\\Jobs\\Job->fire()
#18 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(306): Illuminate\\Queue\\Worker->process('database', Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Object(Illuminate\\Queue\\WorkerOptions))
#19 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(132): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), 'database', Object(Illuminate\\Queue\\WorkerOptions))
#20 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon('database', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#21 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker('database', 'default')
#22 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#23 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#24 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#25 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#26 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#27 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#28 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
#29 /Users/mathewparet/Projects/vpn-self-service/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#30 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#31 /Users/mathewparet/Projects/vpn-self-service/vendor/symfony/console/Application.php(912): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 /Users/mathewparet/Projects/vpn-self-service/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 /Users/mathewparet/Projects/vpn-self-service/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#35 /Users/mathewparet/Projects/vpn-self-service/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(130): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#36 /Users/mathewparet/Projects/vpn-self-service/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#37 {main}
"} 
```

I did a bit of debugging on ```PusherBroadcaster.php``` and found that error is thrown from the broadcast method and the values of each variable passed to ```$this->pusher->trigger()``` seems ok except that ```$socket``` is null. I assume this is what is causing the trigger to fail.

```
public function broadcast(array $channels, $event, array $payload = [])
    {
        $socket = Arr::pull($payload, 'socket');

        $response = $this->pusher->trigger(
            $this->formatChannels($channels), $event, $payload, $socket, true
        );

        if ((is_array($response) && $response['status'] >= 200 && $response['status'] <= 299)
            || $response === true) {
            return;
        }

        throw new BroadcastException(
            is_bool($response) ? 'Failed to connect to Pusher.' : $response['body']
        );
    }
```

I am stuck and I do not know how to move forward.

**Comment by rennokki** [comment]
Downgrade to pusher PHP package to `4.1.3`
