### ISSUE TITLE
Periodic emergency logs filling log files

### ISSUE THREAD

**Issue by Loom3** [beyondcode/laravel-websockets#566]
Getting the following exception periodically. Fills up log space after a while:

```
[2020-09-30 23:18:29] production.EMERGENCY: Illuminate\Broadcasting\BroadcastException in /home/www/html/FITO/vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/PusherBroadcas
ter.php:121
Stack trace:
#0 /home/www/html/FITO/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastEvent.php(64): Illuminate\Broadcasting\Broadcasters\PusherBroadcaster->broadcast(Array, 'App\\Events\\Com
m...', Array)
#1 [internal function]: Illuminate\Broadcasting\BroadcastEvent->handle(Object(Illuminate\Broadcasting\Broadcasters\PusherBroadcaster))
#2 /home/www/html/FITO/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#3 /home/www/html/FITO/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#4 /home/www/html/FITO)/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#5 /home/www/html/FITO/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Arr
ay, Object(Closure))...
```

I've tested each of the broadcast areas but can't duplicate at will. Seems random.
What could be causing this?

Thanks

Laravel 6 CentOS 7

**Comment by rennokki** [comment]
The server files do not get hit in the stacktraces, so make sure to check the logging docs on Laravel: https://laravel.com/docs/8.x/logging

**Comment by Loom3** [comment]
Was not getting these errors before Laravel Websockets was turned on.
