### ISSUE TITLE
Connecting to pusher.com instead of my instance

### ISSUE THREAD

**Issue by spekulatius** [beyondcode/laravel-websockets#571]
Hello @rennokki,

after initially having everything up and working, I've had to upgrade the dependencies to PHP7.4 and with this a new issue came up. While the `websockets:serve` is running, the site is now connecting to sockjs.pusher.com instead of my instance.

I guess it's an issue in the configuration, so I'll share the relevant parts below. If something else is required please let me know!

## Configuration

env file:

```
BROADCAST_DRIVER=pusher

# ...

# Adjusted, but similar:
PUSHER_APP_ID=432746436346
PUSHER_APP_KEY=2a53nr42et52d5m
PUSHER_APP_SECRET=sh3j5ua9p1atj

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
```

`connections` in `config/broadcasting.php`:

```
        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'useTLS' => true,
                'encrypted' => true,
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => 'http'
            ],
        ]
```

`config/websockets.php`:

```
<?php

use BeyondCode\LaravelWebSockets\Dashboard\Http\Middleware\Authorize;

return [

    /*
     * Set a custom dashboard configuration
     */
    'dashboard' => [
        'port' => env('LARAVEL_WEBSOCKETS_PORT', 6001),
    ],

    /*
     * This package comes with multi tenancy out of the box. Here you can
     * configure the different apps that can use the webSockets server.
     *
     * Optionally you specify capacity so you can limit the maximum
     * concurrent connections for a specific app.
     *
     * Optionally you can disable client events so clients cannot send
     * messages to each other via the webSockets.
     */
    'apps' => [
        [
            'id' => env('PUSHER_APP_ID'),
            'name' => env('APP_NAME'),
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'enable_client_messages' => false,
            'enable_statistics' => true,
        ],
    ],

    /*
     * This class is responsible for finding the apps. The default provider
     * will use the apps defined in this config file.
     *
     * You can create a custom provider by implementing the
     * `AppProvider` interface.
     */
    'app_provider' => BeyondCode\LaravelWebSockets\Apps\ConfigAppProvider::class,

    /*
     * This array contains the hosts of which you want to allow incoming requests.
     * Leave this empty if you want to accept requests from all hosts.
     */
    'allowed_origins' => [
        'STAGING.HOST.com',
        'HOST.com',
    ],

    /*
     * The maximum request size in kilobytes that is allowed for an incoming WebSocket request.
     */
    'max_request_size_in_kb' => 250,

    /*
     * This path will be used to register the necessary routes for the package.
     */
    'path' => 'laravel-websockets',

    /*
     * Dashboard Routes Middleware
     *
     * These middleware will be assigned to every dashboard route, giving you
     * the chance to add your own middleware to this list or change any of
     * the existing middleware. Or, you can simply stick with this list.
     */
    'middleware' => [
        'web',
        Authorize::class,
    ],

    'statistics' => [
        /*
         * This model will be used to store the statistics of the WebSocketsServer.
         * The only requirement is that the model should extend
         * `WebSocketsStatisticsEntry` provided by this package.
         */
        'model' => \BeyondCode\LaravelWebSockets\Statistics\Models\WebSocketsStatisticsEntry::class,

        /**
         * The Statistics Logger will, by default, handle the incoming statistics, store them
         * and then release them into the database on each interval defined below.
         */
        'logger' => BeyondCode\LaravelWebSockets\Statistics\Logger\HttpStatisticsLogger::class,

        /*
         * Here you can specify the interval in seconds at which statistics should be logged.
         */
        'interval_in_seconds' => 60,

        /*
         * When the clean-command is executed, all recorded statistics older than
         * the number of days specified here will be deleted.
         */
        'delete_statistics_older_than_days' => 60,

        /*
         * Use an DNS resolver to make the requests to the statistics logger
         * default is to resolve everything to 127.0.0.1.
         */
        'perform_dns_lookup' => false,
    ],

    /*
     * Define the optional SSL context for your WebSocket connections.
     * You can see all available options at: http://php.net/manual/en/context.ssl.php
     */
    'ssl' => [
        /*
         * Path to local certificate file on filesystem. It must be a PEM encoded file which
         * contains your certificate and private key. It can optionally contain the
         * certificate chain of issuers. The private key also may be contained
         * in a separate file specified by local_pk.
         */
        'local_cert' => env('LARAVEL_WEBSOCKETS_SSL_LOCAL_CERT', null),

        /*
         * Path to local private key file on filesystem in case of separate files for
         * certificate (local_cert) and private key.
         */
        'local_pk' => env('LARAVEL_WEBSOCKETS_SSL_LOCAL_PK', null),

        /*
         * Passphrase for your local_cert file.
         */
        'passphrase' => env('LARAVEL_WEBSOCKETS_SSL_PASSPHRASE', null),
    ],

    /*
     * Channel Manager
     * This class handles how channel persistence is handled.
     * By default, persistence is stored in an array by the running webserver.
     * The only requirement is that the class should implement
     * `ChannelManager` interface provided by this package.
     */
    'channel_manager' => \BeyondCode\LaravelWebSockets\WebSockets\Channels\ChannelManagers\ArrayChannelManager::class,
];
```

## Code

`bootstrap.js`:

```
import Echo from 'laravel-echo';

window.Pusher = require ('pusher-js');

window.Echo = new Echo({
  broadcaster: 'pusher',
  key: process.env.MIX_PUSHER_APP_KEY,
  wsHost: window.location.hostname,
  wsPort: 6001,
  forceTLS: false,
  disableStats: true,
});
```

## Tried:

 - The site is using Cloudflare, but have tried to switch to dev-mode and setting the origin IP in my host file locally - no change.
 - The site is running on Forge - not sure if this might influence.
 - Switching off the daemon and running it manually. No connections arrived.

## Side Note

The backend logs also show attempts to connect to pusher.com to deliver the notifications - I guess the issue on the frontend affecting the backend as well. Any hints on how to configure it correctly are highly appreciated. 

### Composer

```
PHP 7.4.10
laravel/framework                   v7.28.3
beyondcode/laravel-websockets       1.8.1
pusher/pusher-php-server            v4.1.4
```

### NPM

```
pusher-js@^7.0.0
laravel-echo@^1.8.1
```

Cheers,
Peter

**Comment by myckhel** [comment]
try adding this config option `enabledTransports: ['ws', 'wss'],` to your Echo object

**Comment by spekulatius** [comment]
Hey @myckhel 

Thank you for pointing this out. It indeed helped to point the requests at my application. 

Now I struggle with the next issue: The socket server is running, but the requests aren't arriving. I get a 404 on the site.

I've ensured the server firewall to allow the port and even switched Cloudflare off (sockets are already on). Any clues what to look at?

Again, thank you for you help,

Peter

**Comment by myckhel** [comment]
Oh

Have you tried to visit the websocket dashboard `/laravel-websockets`
- Connect and send custom events to see if it works normally from the server part.

If so i guess server side working  and client side would need debugging

**Comment by spekulatius** [comment]
Hey @myckhel 

thanks for pointing me to the dashboard! Good idea to check! Here are my findings:

- I can connect - it works as expected. That's already more than I get on the website. This lead me to look closer at the issue of the website not connecting and I've noticed that my site is returning 404 as Echo is attempting to connect on 443 (SSL) instead of 6001 (websockets). I've fixed this by adding 'wssPort': 6001 to the Echo configuration.

- I can't send messages on the dashboard or from the application. I guess the application is attempting to send via pusher.com... I get a 500 error back with this:

```
[2020-10-08 10:03:14] production.ERROR: Failed to connect to Pusher. {"userId":1,"exception":"[object] (Illuminate\\Broadcasting\\BroadcastException(code: 0): Failed to connect to Pusher. at /home/project/project.com/vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php:121)
[stacktrace]
#0 /home/project/project.com/vendor/beyondcode/laravel-websockets/src/Dashboard/Http/Controllers/SendMessage.php(26): Illuminate\\Broadcasting\\Broadcasters\\PusherBroadcaster->broadcast()
#1 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): BeyondCode\\LaravelWebSockets\\Dashboard\\Http\\Controllers\\SendMessage->__invoke()
#2 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#3 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
#4 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
#5 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#6 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#7 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#8 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#9 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#10 /home/project/project.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#12 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#14 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#15 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#17 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#19 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then()
#21 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()
#22 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute()
#23 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()
#24 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()
#25 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#26 /home/project/project.com/vendor/laravel/nova/src/Http/Middleware/ServeNova.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\ServeNova->handle()
#28 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#30 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#32 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#34 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#36 /home/project/project.com/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#38 /home/project/project.com/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#40 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()
#42 /home/project/project.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#43 /home/project/project.com/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#44 {main}
"} 
```

Any great points on how to configure the backend application to use the local websockets server too @myckhel ?

Once more, thank you for your help! I wouldn't been that far without it!

Cheers,
Peter

**Comment by rbreahna** [comment]
Having a similar problem on laravel 8, although only on localhost, previously it worked, no changes in config

**Comment by myckhel** [comment]
Maybe you are missing this config option in Echo object `key: PUSHER_KEY` that could be the reason for the error.

**Comment by spekulatius** [comment]
> Maybe the pusher key is not correct `key: PUSHER_KEY` that could be the reason for the error.
> try to log your pusher key or confirm its the exact

Shouldn't the key be irrelevant when using this websocket module?

**Comment by myckhel** [comment]
> > Maybe the pusher key is not correct `key: PUSHER_KEY` that could be the reason for the error.
> > try to log your pusher key or confirm its the exact
> 
> Shouldn't the key be irrelevant when using this websocket module?

weeeew im not sure but i think its better to follow the pusher way.

**Comment by spekulatius** [comment]
> weeeew im not sure but i think its better to follow the pusher way.

Hmmmmm, I'm keen to make it work with this package. I've googled already but couldn't find anything solving my issue.

**Comment by myckhel** [comment]
Checking the line error came from.
https://github.com/beyondcode/laravel-websockets/blob/c85ec38452f8dfdad4310dc22af19108f89fa9fe/src/Dashboard/Http/Controllers/SendMessage.php#L26

It seems the data from the dashboard is not a json.


I hope you put a valid json in the data input e.g `{"key": "value"}`
Before you pressed the send button.

**Comment by spekulatius** [comment]
Yup, I've made sure it's a json. It also throws an error, if you enter something else @myckhel

**Comment by rennokki** [comment]
If you use `'useTLS' => true`, you might as well change the `scheme` to `https`

**Comment by damieneskimo** [comment]
It might not be helpful, but I had the same issue and in my case, the `host` in the pusher config was wrong. If you are using homestead on your local, please check `host` is set to your local host name or ip

**Comment by spekulatius** [comment]
Hey @damieneskimo 

I've resolve it by now. Plus a few other issues I've noticed along the way. Thanks for pointing it out, in a similar hope to make the search easier for others I've written a [little blogs post](https://releasecandidate.dev/posts/2020/common-issues-with-beyondcode-laravel-websockets/) about the issues I've solved. Maybe it helps someone...

Cheers,
Peter
