### ISSUE TITLE
Backward compatibility break

### ISSUE THREAD

**Issue by afilippov1985** [beyondcode/laravel-websockets#705]
I'm using `laravel/framework:v7.30.4`
This [commit](https://github.com/beyondcode/laravel-websockets/commit/72e45815a8447d2b5d359e67459094bb9bb94ebd)  by @Koozza  breaks something due to incompatible changes in `pusher/pusher-php-server:5.0`

[compare 1.9.0...1.10.0](https://github.com/beyondcode/laravel-websockets/compare/1.9.0...1.10.0)

Reverting to `pusher/pusher-php-server:4.1.5` helps

```
PHP Warning:  array_merge(): Expected parameter 2 to be an array, null given in /var/www/api/vendor/pusher/pusher-php-server/src/Pusher.php on line 518
```

```
[2021-03-01 09:23:49] production.ERROR: Cannot use object of type stdClass as array {"exception":"[object] (Error(code: 0): Cannot use object of type stdClass as array at /var/www/api/vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php:122)
[stacktrace]
#0 /var/www/api/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastEvent.php(64): Illuminate\\Broadcasting\\Broadcasters\\PusherBroadcaster->broadcast()
#1 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Broadcasting\\BroadcastEvent->handle()
#2 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#4 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#5 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#6 /var/www/api/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call()
#7 /var/www/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#8 /var/www/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#9 /var/www/api/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then()
#10 /var/www/api/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\\Bus\\Dispatcher->dispatchNow()
#11 /var/www/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#12 /var/www/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /var/www/api/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\\Pipeline\\Pipeline->then()
#14 /var/www/api/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#15 /var/www/api/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#16 /var/www/api/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\\Queue\\Jobs\\Job->fire()
#17 /var/www/api/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(306): Illuminate\\Queue\\Worker->process()
#18 /var/www/api/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(132): Illuminate\\Queue\\Worker->runJob()
#19 /var/www/api/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon()
#20 /var/www/api/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#21 /var/www/api/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\\Queue\\Console\\WorkCommand->handle()
#22 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\WorkCommand->handle()
#23 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#24 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#25 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#26 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#27 /var/www/api/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#28 /var/www/api/vendor/symfony/console/Command/Command.php(256): Illuminate\\Console\\Command->execute()
#29 /var/www/api/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#30 /var/www/api/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run()
#31 /var/www/api/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand()
#32 /var/www/api/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun()
#33 /var/www/api/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#34 /var/www/api/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#35 /var/www/api/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#36 {main}
```

**Comment by Koozza** [comment]
Hi! Thanks for the mention :) 

Laravel 7.x itself is not compatible with Pusher 5.x, thats why you get this error. @rennokki Maybe we should add the illuminate constrained as we talked about in https://github.com/beyondcode/laravel-websockets/pull/698 to prevent the above from happening.

I thought that the laravel constraint was specific enough, but apparently not.
