### ISSUE TITLE
get_object_vars() expects parameter 1 to be object, array given

### ISSUE THREAD

**Issue by BasvanH** [beyondcode/laravel-websockets#797]
Hi,

I'm using:
|Package|Version|
| ----------- | ----------- |
|beyondcode/laravel-websockets |1.12.0|
|laravel/framework|v8.49.1|
|pusher/pusher-php-server|5.0.3|

When sending a broadcast message to a single channel, I get a warning. This happend after upgrading to Laravel 8.

```
[2021-07-09T08:15:37.918787+02:00] [s:] [u:0] [c:124] [p:0] local.ERROR: get_object_vars() expects parameter 1 to be object, array given {"details":"#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 ...\\vendor\\pusher\\pusher-php-server\\src\\Pusher.php(539): get_object_vars()
#2 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Broadcasting\\Broadcasters\\PusherBroadcaster.php(125): Pusher\\Pusher->trigger()
#3 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Broadcasting\\BroadcastEvent.php(71): Illuminate\\Broadcasting\\Broadcasters\\PusherBroadcaster->broadcast()
#4 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Illuminate\\Broadcasting\\BroadcastEvent->handle()
#5 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#6 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#7 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#8 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(651): Illuminate\\Container\\BoundMethod::call()
#9 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Bus\\Dispatcher.php(128): Illuminate\\Container\\Container->call()
#10 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#11 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Bus\\Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#13 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Broadcasting\\BroadcastManager.php(116): Illuminate\\Bus\\Dispatcher->dispatchNow()
#14 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(308): Illuminate\\Broadcasting\\BroadcastManager->queue()
#15 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(231): Illuminate\\Events\\Dispatcher->broadcastEvent()
#16 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\helpers.php(450): Illuminate\\Events\\Dispatcher->dispatch()
#17 ...\\app\\Jobs\\OrderRevenueUpdateJob.php(72): event()
#18 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): App\\Jobs\\OrderRevenueUpdateJob->handle()
#19 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#20 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#21 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#22 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(651): Illuminate\\Container\\BoundMethod::call()
#23 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Bus\\Dispatcher.php(128): Illuminate\\Container\\Container->call()
#24 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#25 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Bus\\Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#27 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\CallQueuedHandler.php(120): Illuminate\\Bus\\Dispatcher->dispatchNow()
#28 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#29 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then()
#31 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#32 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Jobs\\Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#33 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(428): Illuminate\\Queue\\Jobs\\Job->fire()
#34 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(378): Illuminate\\Queue\\Worker->process()
#35 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(329): Illuminate\\Queue\\Worker->runJob()
#36 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Console\\WorkCommand.php(117): Illuminate\\Queue\\Worker->runNextJob()
#37 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Console\\WorkCommand.php(101): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#38 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#39 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#40 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#41 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#42 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(651): Illuminate\\Container\\BoundMethod::call()
#43 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(136): Illuminate\\Container\\Container->call()
#44 ...\\vendor\\symfony\\console\\Command\\Command.php(299): Illuminate\\Console\\Command->execute()
#45 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#46 ...\\vendor\\symfony\\console\\Application.php(978): Illuminate\\Console\\Command->run()
#47 ...\\vendor\\symfony\\console\\Application.php(295): Symfony\\Component\\Console\\Application->doRunCommand()
#48 ...\\vendor\\symfony\\console\\Application.php(167): Symfony\\Component\\Console\\Application->doRun()
#49 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(92): Symfony\\Component\\Console\\Application->run()
#50 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(129): Illuminate\\Console\\Application->run()
#51 ...\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#52 {main}"} {"file":"...\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\Logger.php","line":183,"class":"Illuminate\\Log\\Logger","function":"writeLog"}
```

This is my class, nothing special.
```
class SendMessageToUser implements ShouldBroadcastNow
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $broadcastQueue = 'notifications';
    public $user;
    public $message;
    public $result;
    public $data;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct($user, $message, $result = 'info', $data = null)
    {
        $this->user = $user;
        $this->message = $message;
        $this->result = $result;
        $this->data = $data;
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return \Illuminate\Broadcasting\Channel|array
     */
    public function broadcastOn()
    {
        return new Channel('user.' . $this->user->id);
    }

    public function broadcastWith()
    {
        return [
            'result' => $this->result,
            'message' => $this->message,
            'data' => $this->data
        ];
    }
}
```

**Comment by simonbuehler** [comment]
i guess php 8 need at least 2.* see 35a0e3e8226b6b57f5cf44c2303a9e803c892c00

**Comment by BasvanH** [comment]
> i guess php 8 need at least 2.* see [35a0e3e](https://github.com/beyondcode/laravel-websockets/commit/35a0e3e8226b6b57f5cf44c2303a9e803c892c00)

I'm on PHP 7.4.13

**Comment by simonbuehler** [comment]
sorry my bad, but where in the stacktrace is laravel-websockets? i only see pusher-php-server ?

**Comment by BasvanH** [comment]
Hm, true, thats my bad. So I guess I need to go to https://github.com/pusher/pusher-http-php ?

**Comment by tobischulz** [comment]
Hey, got the very same error. Updated the pusher/pusher-php-server to version 6.0 fixed that for me.

**Comment by BasvanH** [comment]
@tobischulz, thanks for letting me know. I'e updated to PHP8 and then the error also went away.
