### ISSUE TITLE
QueueServiceProvider error logged within application

### ISSUE THREAD

**Issue by erickneverson** [beyondcode/laravel-websockets#949]
Horizon shows my listener job processed successfully but the event fails.  Here's what my the log shows:

```
local.ERROR: array_key_exists() expects parameter 2 to be array, null given {"exception":"[object] (ErrorException(code: 0): array_key_exists() expects parameter 2 to be array, null given at /var/www/vendor/laravel/framework/src/Illuminate/Queue/QueueServiceProvider.php:238)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/vendor/laravel/framework/src/Illuminate/Queue/QueueServiceProvider.php(238): array_key_exists()
#2 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(873): Illuminate\\Queue\\QueueServiceProvider->Illuminate\\Queue\\{closure}()
```

**Here is what horizon log hows**

```
Illuminate\Broadcasting\BroadcastException: Pusher error: . in /var/www/vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php:128
```

**Here's now I trigger my event:**

```
event(new ImportProgressUpdated(300,300,'100%'));
```
***or***
```
ImportProgressUpdated::dispatch(300,300,'100%');
```

**EventServiceProvider**
```
protected $listen = [
        ImportProgressUpdated::class => [
            SendImportJobProgressNotification::class,
        ],
    ];
```

**My event**

```
<?php

namespace App\Events;

use Illuminate\Broadcasting\Channel;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Broadcasting\PrivateChannel;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\SerializesModels;

class ImportProgressUpdated implements ShouldBroadcast
{
    use Dispatchable;
    use InteractsWithSockets;
    use SerializesModels;

    public $connection = 'redis';
    public $queue = 'Pusher';

    public int $companyId;
    public int $jobNumber;
    public string $percentComplete;

    public function __construct(int $companyId, int $jobNumber, string $percentComplete)
    {
        $this->companyId = $companyId;
        $this->jobNumber = $jobNumber;
        $this->percentComplete = $percentComplete;
    }

    public function broadcastAs()
    {
        return 'import-progress-updated';
    }

    public function broadcastOn()
    {
        //return new PrivateChannel(sprintf('company.%d',[$this->companyId])); // todo use this
        return new Channel(sprintf('company.%d', [$this->companyId]));
    }

    public function broadcastWith()
    {
        return [
            'company_id'       => $this->companyId,
            'job_number'       => $this->jobNumber,
            'percent_complete' => $this->percentComplete,
        ];
    }
}

```

I don't have a front end yet to verify successful dispatch as I was planning to use Postman to connect to the websocket. Any thoughts?

**Comment by erickneverson** [comment]
I believe my issue has been resolved by removing special characters from the required env fields:
PUSHER_APP_ID
PUSHER_APP_KEY
PUSHER_APP_SECRET
